---

# Set nsswitch_enabled to True for the role to make any changes
nsswitch_enabled: False
# Default location of the config file
nsswitch_file_location: /etc/nsswitch.conf

# Aliases
nsswitch_aliases:
  - files

# Automount
nsswitch_automount:
  - files

# Bootparams
nsswitch_bootparams:
  - files

# Ethers
nsswitch_ethers:
  - files

# Group
nsswitch_group:
  - files
  - systemd

# Hosts
nsswitch_hosts:
  - files
  - dns
  - myhostname

# Init groups
nsswitch_initgroups:
  - files

# Net groups
nsswitch_netgroup:
  - files

# Netmasks
nsswitch_netmasks:
  - files

# Networks
nsswitch_networks:
  - files

# Passwd
nsswitch_passwd:
  - files
  - systemd

# Protocols
nsswitch_protocols:
  - files

# Publickey
nsswitch_publickey:
  - files

# RPC
nsswitch_rpc:
  - files

# Services
nsswitch_services:
  - files

# Shadow
nsswitch_shadow:
  - files

# List of all databases
nsswitch__all:
  aliases: "{{ nsswitch_aliases }}"
  automount: "{{ nsswitch_automount }}"
  bootparams: "{{ nsswitch_bootparams }}"
  ethers: "{{ nsswitch_ethers }}"
  group: "{{ nsswitch_group }}"
  hosts: "{{ nsswitch_hosts }}"
#  initgroups: "{{ nsswitch_initgroups }}"
  netgroup: "{{ nsswitch_netgroup }}"
  netmasks: "{{ nsswitch_netmasks }}"
  networks: "{{ nsswitch_networks }}"
  passwd: "{{ nsswitch_passwd }}"
  protocols: "{{ nsswitch_protocols }}"
  publickey: "{{ nsswitch_publickey }}"
  rpc: "{{ nsswitch_rpc }}"
  services: "{{ nsswitch_services }}"
  shadow: "{{ nsswitch_shadow }}"

# Final configuration
nsswitch_config: "{{ nsswitch__all }}"
